
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbtfezcqvkoeacufvuro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhidGZlemNxdmtvZWFjdWZ2dXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDM3NjAsImV4cCI6MjA2MDM3OTc2MH0.DWEDptxCaaLQlKUaPu5A5fdMsntRwurnonZHYv3Knzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
